services:
  - type: web
    name: maharat-line-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false