services:
  - type: web
    name: line-chatbot-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: LINE_CHANNEL_SECRET
        generateValue: true
      - key: LINE_CHANNEL_ACCESS_TOKEN
        generateValue: true